name: PythonCI

on: [push]

jobs:
  run:
    runs-on: windows-latest
    env:
      OS: windows-latest
      PYTHON: "3.12"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "2"
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Generate Report
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt coverage pytest pytest-cov
    - name: Run tests and collect coverage
      run: coverage run -m unittest $(git ls-files '*.py') # pytest --cov-report xml --cov=. ./local/payload/irc.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
