name: PythonCI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "2"
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate Report
      run: |
        python -m pip install coverage pytest pytest-cov
        coverage run -m unittest
    - name: Run tests and collect coverage
      run: |
        export PYTHONPATH=. pytest # $(git ls-files '*.py')
        python -m pytest --cov-report xml ./local/payload/irc.py
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
