name: Snyk
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 1 * 5"
permissions:
  contents: read
jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    environment: SNYK_API_TOKEN
    env:
      KEY: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Snyk & Authenticate
        run: sudo yarn global add snyk; snyk auth ${KEY}
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@14818c4695ecc4045f33c9cee9e795a788711ca4
      - name: Run Snyk code
        run: snyk code test --sarif > snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
