name: Snyk

on:
  push:
    branches: [ "main" ] # pull_request
  schedule:
    - cron: "34 2 * * 0"

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          echo ${SNYK_TOKEN:0:4}
          snyk auth ${SNYK_TOKEN}
      - name: Run Snyk to check configuration files for security issues
        continue-on-error: true
        uses: snyk/actions/iac@14818c4695ecc4045f33c9cee9e795a788711ca4
      - name: Run Snyk code
        run: snyk code test --sarif > snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with: 
          sarif_file: snyk.sarif
